// +build !generator

// Code generated by generator api. DO NOT EDIT.

package flowexec

import (
	context "context"
	fmt "fmt"
	http "net/http"

	flowexectypes "github.com/olvrng/rbot/be/com/flowexec/types"
	httprpc "github.com/olvrng/rbot/be/pkg/httprpc"
)

func init() {
	httprpc.Register(NewServer)
}

func NewServer(builder interface{}, hooks ...httprpc.HooksBuilder) (httprpc.Server, bool) {
	switch builder := builder.(type) {
	case func() MessengerService:
		return NewMessengerServiceServer(builder, hooks...), true
	case MessengerService:
		fn := func() MessengerService { return builder }
		return NewMessengerServiceServer(fn, hooks...), true
	case func() OrderService:
		return NewOrderServiceServer(builder, hooks...), true
	case OrderService:
		fn := func() OrderService { return builder }
		return NewOrderServiceServer(fn, hooks...), true
	default:
		return nil, false
	}
}

type MessengerServiceServer struct {
	hooks   httprpc.HooksBuilder
	builder func() MessengerService
}

func NewMessengerServiceServer(builder func() MessengerService, hooks ...httprpc.HooksBuilder) httprpc.Server {
	return &MessengerServiceServer{
		hooks:   httprpc.ChainHooks(hooks...),
		builder: builder,
	}
}

const MessengerServicePathPrefix = "/api/flow/exec/messenger/"

const Path_Messenger_ReceivedMessage = "/api/flow/exec/messenger/ReceivedMessage"
const Path_Messenger_ReceivedPostback = "/api/flow/exec/messenger/ReceivedPostback"

func (s *MessengerServiceServer) PathPrefix() string {
	return MessengerServicePathPrefix
}

func (s *MessengerServiceServer) WithHooks(hooks httprpc.HooksBuilder) httprpc.Server {
	result := *s
	result.hooks = httprpc.ChainHooks(s.hooks, hooks)
	return &result
}

func (s *MessengerServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	hooks := httprpc.WrapHooks(s.hooks)
	ctx, info := req.Context(), &httprpc.HookInfo{Route: req.URL.Path, HTTPRequest: req}
	ctx, err := hooks.RequestReceived(ctx, *info)
	if err != nil {
		httprpc.WriteError(ctx, resp, hooks, *info, err)
		return
	}
	serve, err := httprpc.ParseRequestHeader(req)
	if err != nil {
		httprpc.WriteError(ctx, resp, hooks, *info, err)
		return
	}
	reqMsg, exec, err := s.parseRoute(req.URL.Path, hooks, info)
	if err != nil {
		httprpc.WriteError(ctx, resp, hooks, *info, err)
		return
	}
	serve(ctx, resp, req, hooks, info, reqMsg, exec)
}

func (s *MessengerServiceServer) parseRoute(path string, hooks httprpc.Hooks, info *httprpc.HookInfo) (reqMsg httprpc.Message, _ httprpc.ExecFunc, _ error) {
	switch path {
	case "/api/flow/exec/messenger/ReceivedMessage":
		msg := &flowexectypes.ReceivedMessageRequest{}
		fn := func(ctx context.Context) (newCtx context.Context, resp httprpc.Message, err error) {
			inner := s.builder()
			info.Request, info.Inner = msg, inner
			newCtx, err = hooks.RequestRouted(ctx, *info)
			if err != nil {
				return
			}
			resp, err = inner.ReceivedMessage(newCtx, msg)
			return
		}
		return msg, fn, nil
	case "/api/flow/exec/messenger/ReceivedPostback":
		msg := &flowexectypes.ReceivedPostbackRequest{}
		fn := func(ctx context.Context) (newCtx context.Context, resp httprpc.Message, err error) {
			inner := s.builder()
			info.Request, info.Inner = msg, inner
			newCtx, err = hooks.RequestRouted(ctx, *info)
			if err != nil {
				return
			}
			resp, err = inner.ReceivedPostback(newCtx, msg)
			return
		}
		return msg, fn, nil
	default:
		msg := fmt.Sprintf("no handler for path %q", path)
		return nil, nil, httprpc.BadRouteError(msg, "POST", path)
	}
}

type OrderServiceServer struct {
	hooks   httprpc.HooksBuilder
	builder func() OrderService
}

func NewOrderServiceServer(builder func() OrderService, hooks ...httprpc.HooksBuilder) httprpc.Server {
	return &OrderServiceServer{
		hooks:   httprpc.ChainHooks(hooks...),
		builder: builder,
	}
}

const OrderServicePathPrefix = "/api/flow/exec/order/"

const Path_Order_ReceivedCompletedOrder = "/api/flow/exec/order/ReceivedCompletedOrder"

func (s *OrderServiceServer) PathPrefix() string {
	return OrderServicePathPrefix
}

func (s *OrderServiceServer) WithHooks(hooks httprpc.HooksBuilder) httprpc.Server {
	result := *s
	result.hooks = httprpc.ChainHooks(s.hooks, hooks)
	return &result
}

func (s *OrderServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	hooks := httprpc.WrapHooks(s.hooks)
	ctx, info := req.Context(), &httprpc.HookInfo{Route: req.URL.Path, HTTPRequest: req}
	ctx, err := hooks.RequestReceived(ctx, *info)
	if err != nil {
		httprpc.WriteError(ctx, resp, hooks, *info, err)
		return
	}
	serve, err := httprpc.ParseRequestHeader(req)
	if err != nil {
		httprpc.WriteError(ctx, resp, hooks, *info, err)
		return
	}
	reqMsg, exec, err := s.parseRoute(req.URL.Path, hooks, info)
	if err != nil {
		httprpc.WriteError(ctx, resp, hooks, *info, err)
		return
	}
	serve(ctx, resp, req, hooks, info, reqMsg, exec)
}

func (s *OrderServiceServer) parseRoute(path string, hooks httprpc.Hooks, info *httprpc.HookInfo) (reqMsg httprpc.Message, _ httprpc.ExecFunc, _ error) {
	switch path {
	case "/api/flow/exec/order/ReceivedCompletedOrder":
		msg := &flowexectypes.ReceivedCompletedOrderRequest{}
		fn := func(ctx context.Context) (newCtx context.Context, resp httprpc.Message, err error) {
			inner := s.builder()
			info.Request, info.Inner = msg, inner
			newCtx, err = hooks.RequestRouted(ctx, *info)
			if err != nil {
				return
			}
			resp, err = inner.ReceivedCompletedOrder(newCtx, msg)
			return
		}
		return msg, fn, nil
	default:
		msg := fmt.Sprintf("no handler for path %q", path)
		return nil, nil, httprpc.BadRouteError(msg, "POST", path)
	}
}
